In [1]:
import os
import pandas as pd
import sodapy as Socrata

In [2]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas
# pip install sodapy

import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
#client = Socrata("data.cityofchicago.org", None)

# Example authenticated client (needed for non-public datasets):
client = Socrata('data.cityofchicago.org',
                'OAtaZgqYsVBUqhl9a1bqe3Pzy',
                  username="username",
                  password="password")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("8pix-ypme", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

In [7]:
results_df.head()

,stop_id,direction_id,stop_name,station_name,station_descriptive_name,map_id,ada,red,blue,g,...,p,y,pnk,o,location,:@computed_region_awaf_s7ux,:@computed_region_6mkv_f3dw,:@computed_region_vrxf_vc4k,:@computed_region_bdys_3d7i,:@computed_region_43wa_7qmu
0,30162,W,18th (54th/Cermak-bound),18th,18th (Pink Line),40830,True,False,False,False,...,False,False,True,False,"{'latitude': '41.857908', 'longitude': '-87.66...",8,14920,33,343,26
1,30161,E,18th (Loop-bound),18th,18th (Pink Line),40830,True,False,False,False,...,False,False,True,False,"{'latitude': '41.857908', 'longitude': '-87.66...",8,14920,33,343,26
2,30022,N,35th/Archer (Loop-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,...,False,False,False,True,"{'latitude': '41.829353', 'longitude': '-87.68...",26,14924,56,719,1
3,30023,S,35th/Archer (Midway-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,...,False,False,False,True,"{'latitude': '41.829353', 'longitude': '-87.68...",26,14924,56,719,1
4,30213,N,35-Bronzeville-IIT (Harlem-bound),35th-Bronzeville-IIT,35th-Bronzeville-IIT (Green Line),41120,True,False,False,True,...,False,False,False,False,"{'latitude': '41.831677', 'longitude': '-87.62...",12,21194,1,25,9

In [10]:
orange_stations=results_df[results_df['o']==True]
orange_stations

,stop_id,direction_id,stop_name,station_name,station_descriptive_name,map_id,ada,red,blue,g,...,p,y,pnk,o,location,:@computed_region_awaf_s7ux,:@computed_region_6mkv_f3dw,:@computed_region_vrxf_vc4k,:@computed_region_bdys_3d7i,:@computed_region_43wa_7qmu
2,30022,N,35th/Archer (Loop-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,...,False,False,False,True,"{'latitude': '41.829353', 'longitude': '-87.68...",26,14924,56,719,1
3,30023,S,35th/Archer (Midway-bound),35th/Archer,35th/Archer (Orange Line),40120,True,False,False,False,...,False,False,False,True,"{'latitude': '41.829353', 'longitude': '-87.68...",26,14924,56,719,1
27,30132,S,Adams/Wabash (Inner Loop),Adams/Wabash,"Adams/Wabash (Brown, Green, Orange, Pink & Pur...",40680,False,False,False,True,...,True,False,True,True,"{'latitude': '41.879507', 'longitude': '-87.62...",22,14912,38,367,36
40,30206,S,Ashland (Midway-bound),Ashland,Ashland (Orange Line),41060,True,False,False,False,...,False,False,False,True,"{'latitude': '41.839234', 'longitude': '-87.66...",26,14920,33,126,26
41,30205,N,Ashland (Loop-bound),Ashland,Ashland (Orange Line),41060,True,False,False,False,...,False,False,False,True,"{'latitude': '41.839234', 'longitude': '-87.66...",26,14920,33,126,26
91,30074,E,Clark/Lake (Inner Loop),Clark/Lake,"Clark/Lake (Blue, Brown, Green, Orange, Purple...",40380,True,False,False,True,...,True,False,True,True,"{'latitude': '41.885737', 'longitude': '-87.63...",22,14309,38,92,36
142,30216,S,Halsted (Midway-bound),Halsted,Halsted (Orange Line),41130,True,False,False,False,...,False,False,False,True,"{'latitude': '41.84678', 'longitude': '-87.648...",26,14920,58,59,48
143,30215,N,Halsted (Loop-bound),Halsted,Halsted (Orange Line),41130,True,False,False,False,...,False,False,False,True,"{'latitude': '41.84678', 'longitude': '-87.648...",26,14920,58,59,48
151,30166,W,H.W. Library (Inner Loop),Harold Washington Library-State/Van Buren,Harold Washington Library-State/Van Buren (Bro...,40850,True,False,False,False,...,True,False,True,True,"{'latitude': '41.876862', 'longitude': '-87.62...",48,14913,38,92,10
174,30219,N,Kedzie (Loop-bound),Kedzie,Kedzie (Orange Line),41150,True,False,False,False,...,False,False,False,True,"{'latitude': '41.804236', 'longitude': '-87.70...",49,22248,55,776,8
177,30220,S,Kedzie (Midway-bound),Kedzie,Kedzie (Orange Line),41150,True,False,False,False,...,False,False,False,True,"{'latitude': '41.804236', 'longitude': '-87.70...",49,22248,55,776,8
197,30031,W,LaSalle/Van Buren (Inner Loop),LaSalle/Van Buren,"LaSalle/Van Buren (Brown, Orange, Purple & Pin...",40160,False,False,False,False,...,True,False,True,True,"{'latitude': '41.8768', 'longitude': '-87.6317...",48,14913,38,92,10
210,30182,S,Midway (Arrival),Midway,Midway (Orange Line),40930,True,False,False,False,...,False,False,False,True,"{'latitude': '41.78661', 'longitude': '-87.737...",35,21867,53,86,15
211,30181,N,Midway (Loop-bound),Midway,Midway (Orange Line),40930,True,False,False,False,...,False,False,False,True,"{'latitude': '41.78661', 'longitude': '-87.737...",35,21867,53,86,15
243,30186,S,Pulaski (Midway-bound),Pulaski,Pulaski (Orange Line),40960,True,False,False,False,...,False,False,False,True,"{'latitude': '41.799756', 'longitude': '-87.72...",35,22248,60,793,6
245,30185,N,Pulaski (Loop-bound),Pulaski,Pulaski (Orange Line),40960,True,False,False,False,...,False,False,False,True,"{'latitude': '41.799756', 'longitude': '-87.72...",35,22248,60,793,6
248,30007,N,Quincy/Wells (Inner Loop),Quincy/Wells,"Quincy/Wells (Brown, Orange, Purple & Pink lines)",40040,True,False,False,False,...,True,False,True,True,"{'latitude': '41.878723', 'longitude': '-87.63...",22,14912,38,92,36
257,30081,S,Roosevelt (Midway-63rd-bound),Roosevelt,"Roosevelt (Red, Orange & Green lines)",41400,True,False,False,True,...,False,False,False,True,"{'latitude': '41.867405', 'longitude': '-87.62...",48,14913,34,374,9
258,30080,N,Roosevelt (Loop-Harlem-bound),Roosevelt,"Roosevelt (Red, Orange & Green lines)",41400,True,False,False,True,...,False,False,False,True,"{'latitude': '41.867405', 'longitude': '-87.62...",48,14913,34,374,9
274,30050,E,State/Lake (Inner Loop),State/Lake,"State/Lake (Brown, Green, Orange, Pink & Purpl...",40260,False,False,False,True,...,True,False,True,True,"{'latitude': '41.88574', 'longitude': '-87.627...",22,14309,38,580,36
282,30384,S,Washington/Wabash (Inner Loop),Washington/Wabash,"Washington/Wabash (Brown, Green, Orange, Purpl...",41700,True,False,False,True,...,True,False,True,True,"{'latitude': '41.88322', 'longitude': '-87.626...",22,14310,38,580,36
285,30141,N,Washington/Wells (Inner Loop),Washington/Wells,"Washington/Wells (Brown, Orange, Purple & Pink...",40730,True,False,False,False,...,True,False,True,True,"{'latitude': '41.882695', 'longitude': '-87.63...",22,14310,38,92,36
291,30061,S,Western (Midway-bound),Western,Western (Orange Line),40310,True,False,False,False,...,False,False,False,True,"{'latitude': '41.804546', 'longitude': '-87.68...",19,14924,61,775,3
294,30060,N,Western (Loop-bound),Western,Western (Orange Line),40310,True,False,False,False,...,False,False,False,True,"{'latitude': '41.804546', 'longitude': '-87.68...",19,14924,61,775,3

In [6]:
#get subset of orange line stations
orange_stations=results_df[results_df['o']==True]
orange_stations['stop_id'].unique()

array(['30022', '30023', '30132', '30206', '30205', '30074', '30216',
       '30215', '30166', '30219', '30220', '30031', '30182', '30181',
       '30186', '30185', '30007', '30081', '30080', '30050', '30384',
       '30141', '30061', '30060'], dtype=object)

In [8]:
#get subset of orange line stations
orange_stations=results_df[results_df['o']==True]
orange_stations['station_name'].unique()

array(['35th/Archer', 'Adams/Wabash', 'Ashland', 'Clark/Lake', 'Halsted',
       'Harold Washington Library-State/Van Buren', 'Kedzie',
       'LaSalle/Van Buren', 'Midway', 'Pulaski', 'Quincy/Wells',
       'Roosevelt', 'State/Lake', 'Washington/Wabash', 'Washington/Wells',
       'Western'], dtype=object)

In [11]:
#get subset of orange line stations
orange_stations=results_df[results_df['o']==True]
orange_stations['map_id'].unique()

array(['40120', '40680', '41060', '40380', '41130', '40850', '41150',
       '40160', '40930', '40960', '40040', '41400', '40260', '41700',
       '40730', '40310'], dtype=object)